Email-Service/ForgotPassword.cs, Email-Service/Worker.cs, Libraries/DataLayer/Mongo/Repositories/IUserRepository.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, Libraries/Models/UserAuthentication/ResetPasswordRequest.cs, UsersAPI/Controllers/PasswordController.cs, UsersAPI/ControllersLogic/IPasswordControllerLogic.cs, UsersAPI/ControllersLogic/PasswordControllerLogic.cs
=> #35 forgot password

Email-Service/LockedOutUsers.cs, Email-Service/Worker.cs, Libraries/DataLayer/Mongo/Entities/FailedLoginAttempt.cs, Libraries/DataLayer/Mongo/Entities/User.cs, Libraries/DataLayer/Mongo/Repositories/FailedLoginAttemptRepository.cs, Libraries/DataLayer/Mongo/Repositories/IFailedLoginAttemptRepository.cs, Libraries/DataLayer/Mongo/Repositories/IUserRepository.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, Libraries/Models/UserAuthentication/UnlockUser.cs, UsersAPI/Config/ConfigureServicesHelper.cs, UsersAPI/Controllers/UserLoginController.cs, UsersAPI/ControllersLogic/CreditControllerLogic.cs, UsersAPI/ControllersLogic/IUserLoginControllerLogic.cs, UsersAPI/ControllersLogic/UserLoginControllerLogic.cs, UsersAPI/ControllersLogic/UserRegisterControllerLogic.cs
=> #34 failed login

UsersAPI/Config/ConfigureServicesHelper.cs, UsersAPI/Startup.cs, UsersAPI/UsersAPI.csproj
#4 generate sample documentation for users.
=> #4 configure nswag

Libraries/Encryption/SHA.cs, UsersAPI/Controllers/EncryptionController.cs, UsersAPI/ControllersLogic/EncryptionControllerLogic.cs, UsersAPI/ControllersLogic/IEncryptionControllerLogic.cs
#51 a simple refactor cleared about nearly 75 lines of code.
=> #51 sha refactoring

Libraries/DataLayer/Mongo/Entities/ForgotPasswordAttempt.cs, Libraries/DataLayer/Mongo/Repositories/ForgotPasswordRepository.cs, Libraries/DataLayer/Mongo/Repositories/IForgotPasswordRepository.cs, UsersAPI/Config/ConfigureServicesHelper.cs, UsersAPI/ControllersLogic/PasswordControllerLogic.cs
=> #57 password last 5 times

Common/BenchmarkMethodLogger.cs, Libraries/DataLayer/Mongo/Repositories/IUserRepository.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, UsersAPI/ControllersLogic/UserRegisterControllerLogic.cs
=> #79 prevent duplicate usernames when registering user

Libraries/DataLayer/Mongo/Repositories/ILogRequestRepository.cs, Libraries/DataLayer/Mongo/Repositories/LogRequestRepository.cs, Libraries/Validation/Middleware/RequestLoggingMiddleware.cs, UsersAPI/Config/ConfigureServicesHelper.cs, UsersAPI/ControllersLogic/UserRegisterControllerLogic.cs
=> #78 throttling request user

Tests/Models.Tests/CreditCardValidation.cs, Tests/Models.Tests/Encryption.cs, Tests/Models.Tests/UserAuthentication.cs
=> #90 models tests

Libraries/Validation/UserRegistration/RegisterUserValidation.cs, Tests/Validation.Tests/RegisterUserValidationTests.cs
=> #93 validation unit tests

Libraries/DataLayer/Mongo/Entities/User.cs, Libraries/DataLayer/Mongo/Repositories/IUserRepository.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, Libraries/Models/TwoFactorAuthentication/UpdatePhoneNumber.cs, Libraries/Validation/Middleware/ValidateJWTMiddleware.cs, Libraries/Validation/Phone/PhoneValidator.cs, UsersAPI/Config/ConfigureServicesHelper.cs, UsersAPI/Controllers/TwoFAController.cs, UsersAPI/ControllersLogic/ITwoFAControllerLogic.cs, UsersAPI/ControllersLogic/TwoFAControllerLogic.cs
=> #39 two factor phone settings

Libraries/DataLayer/Mongo/Entities/User.cs
=> #62 adding IsAdmin to User model

Common/Common.csproj, Common/TwilioHelpers/MessageSender.cs, Libraries/DataLayer/Mongo/Entities/HotpCode.cs, Libraries/DataLayer/Mongo/Entities/HotpCodes.cs, Libraries/DataLayer/Mongo/Repositories/HotpCodesRepository.cs, Libraries/DataLayer/Mongo/Repositories/IHotpCodesRepository.cs, Libraries/DataLayer/Mongo/Repositories/IUserRepository.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, Libraries/Models/UserAuthentication/ValidateHotpCode.cs, NETCore-API.sln, Text-Service/Program.cs, Text-Service/Properties/launchSettings.json, Text-Service/Text-Service.csproj, Text-Service/TwoFactorAuthHotpCode.cs, Text-Service/Worker.cs, Text-Service/appsettings.Development.json, Text-Service/appsettings.json, UsersAPI/Config/ConfigureServicesHelper.cs, UsersAPI/Controllers/UserLoginController.cs, UsersAPI/ControllersLogic/IUserLoginControllerLogic.cs, UsersAPI/ControllersLogic/UserLoginControllerLogic.cs, UsersAPI/UsersAPI.csproj
=> #110 create hotp codes

Email-Service/Worker.cs
=> #117 adjusting constructor to use environment variables.

Libraries/DataLayer/Mongo/Repositories/IUserRepository.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, Libraries/Encryption/JWT.cs, Libraries/Validation/Middleware/ValidateJWTMiddleware.cs, UsersAPI/ControllersLogic/UserLoginControllerLogic.cs
=> #118 using public key instead of private key.

Common/Common.csproj, Common/ThirdPartyAPIs/IpInfoHelper.cs, Common/ThirdPartyAPIs/IpInfoResponse.cs, Libraries/DataLayer/Mongo/Entities/SuccessfulLogin.cs, Libraries/DataLayer/Mongo/Repositories/ISuccessfulLoginRepository.cs, Libraries/DataLayer/Mongo/Repositories/SuccessfulLoginRepository.cs, Libraries/Models/UserAuthentication/LoginUser.cs, UsersAPI/Config/ConfigureServicesHelper.cs, UsersAPI/ControllersLogic/UserLoginControllerLogic.cs
=> #130 get ip info

Libraries/DataLayer/Mongo/Entities/SuccessfulLogin.cs, UsersAPI/ControllersLogic/UserLoginControllerLogic.cs
=> #130 adjustments to successful login

Libraries/DataLayer/Mongo/Entities/SuccessfulLogin.cs, Libraries/DataLayer/Mongo/Repositories/ISuccessfulLoginRepository.cs, Libraries/DataLayer/Mongo/Repositories/SuccessfulLoginRepository.cs, Libraries/Models/UserAuthentication/WasLoginMe.cs, Libraries/Validation/Middleware/ValidateJWTMiddleware.cs, UsersAPI/Controllers/UserLoginController.cs, UsersAPI/ControllersLogic/IUserLoginControllerLogic.cs, UsersAPI/ControllersLogic/UserLoginControllerLogic.cs
=> #136 get recent login activity

UsersAPI/ControllersLogic/UserLoginControllerLogic.cs
=> #134 replacinng with Rust unmanaged code

Libraries/Encryption/AESWrapper.cs, Tests/Encryption.Tests/AESWrapperTests.cs
=> #142 exposing Rust dll imports AES256 decrypt and encrypt functionality.

UsersAPI.Tests/UsersAPI.Tests.csproj, UsersAPI/Startup.cs, UsersAPI/UsersAPI.csproj
=> #12 adjusting .net core api to use .NET 6.0

UsersAPI/Controllers/CreditController.cs, UsersAPI/Controllers/EncryptionController.cs, UsersAPI/Controllers/PasswordController.cs, UsersAPI/Controllers/TestController.cs, UsersAPI/Controllers/TwoFAController.cs, UsersAPI/Controllers/UserLoginController.cs, UsersAPI/Controllers/UserRegisterController.cs
=> #150 removing api prefix from controllers

Email-Service/email-service.service
=> #185 adding email service file

API/ControllerLogic/BlogControllerLogic.cs, API/ControllerLogic/IBlogPostControllerLogic.cs, API/Controllers/BlogController.cs, Libraries/DataLayer/Mongo/Repositories/BlogPostRepository.cs, Libraries/DataLayer/Mongo/Repositories/IBlogPostRepository.cs
=> #181 get a list of blog posts.

API/ControllerLogic/UserLoginControllerLogic.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, Libraries/Encryption/JWT.cs
=> #21 refresh token method

API/ControllerLogic/UserLoginControllerLogic.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, Libraries/Encryption/Encryption.csproj, Libraries/Encryption/SCryptWrapper.cs
=> #197 add scrypt

Libraries/DataLayer/Mongo/Repositories/UserRepository.cs
=> #203 remove email activation information after user activates

API/ControllerLogic/BlogControllerLogic.cs, API/ControllerLogic/CreditControllerLogic.cs, API/ControllerLogic/EncryptionControllerLogic.cs, API/ControllerLogic/PasswordControllerLogic.cs, API/ControllerLogic/TwoFAControllerLogic.cs, API/ControllerLogic/UIDataControllerLogic.cs, API/ControllerLogic/UserLoginControllerLogic.cs, API/ControllerLogic/UserRegisterControllerLogic.cs
=> #207 insert exceptions

API/Controllers/TokenController.cs
=> #177 adding token controller

API/ConfigureServicesHelper.cs, API/ControllerLogic/ITokenControllerLogic.cs, API/ControllerLogic/TokenControllerLogic.cs, API/Controllers/TokenController.cs, Libraries/DataLayer/Mongo/Repositories/IUserRepository.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs
=> #177 creating token controller

API/ControllerLogic/ITokenControllerLogic.cs, API/ControllerLogic/TokenControllerLogic.cs, API/Controllers/TokenController.cs
=> #177 check header instead of query string for ApiKey

API/ControllerLogic/ITokenControllerLogic.cs, API/ControllerLogic/IUserLoginControllerLogic.cs, API/ControllerLogic/TokenControllerLogic.cs, API/ControllerLogic/UserLoginControllerLogic.cs, API/Controllers/TokenController.cs, API/Controllers/UserLoginController.cs, Libraries/Encryption/JWT.cs, Libraries/Encryption/RSAProviderWrapper.cs
=> #210 move getrefresh token

API/ControllerLogic/UserLoginControllerLogic.cs, Libraries/Encryption/ECDSAWrapper.cs
=> #216 adding ECDASWrapper

API/ControllerLogic/PasswordControllerLogic.cs, API/ControllerLogic/TokenControllerLogic.cs, API/ControllerLogic/UserLoginControllerLogic.cs, Libraries/Encryption/Encryption.csproj, Libraries/Encryption/JWT.cs, Libraries/Models/Encryption/BcryptVerifyModel.cs, Libraries/Validation/Middleware/ValidateJWTMiddleware.cs
=> #215 bcrypt as a service

API/ControllerLogic/IPasswordControllerLogic.cs, API/ControllerLogic/PasswordControllerLogic.cs, API/Controllers/PasswordController.cs, Libraries/Models/Encryption/SCryptVerifyRequest.cs, Libraries/Models/Encryption/ScryptHashRequest.cs, Libraries/Validation/Middleware/ValidateJWTMiddleware.cs
=> #172 scrypt as a service

Libraries/Encryption/AESWrapper.cs, Tests/Encryption.Tests/AESWrapperTests.cs
=> #225 encrypt and decrypt with aes 256 async

Tests/DataLayer.Tests/UserRepositoryTest.cs, Tests/Validation.Tests/PhoneValidatorTests.cs
=> phone validator test

API/ControllerLogic/UserRegisterControllerLogic.cs, Email-Service/ActivateUser.cs, Libraries/DataLayer/Mongo/Entities/User.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs, Libraries/Validation/UserRegistration/RegisterUserValidation.cs
=> #226 email token refactor

API/ConfigureServicesHelper.cs, API/ControllerLogic/CreditControllerLogic.cs, Email-Service/CCInfoChanged.cs, Email-Service/Worker.cs, Libraries/DataLayer/Mongo/Entities/CreditCardInfoChanged.cs, Libraries/DataLayer/Mongo/Repositories/CreditCardInfoChangedRepository.cs, Libraries/DataLayer/Mongo/Repositories/ICreditCardInfoChangedRepository.cs, Payments/StripTokenCard.cs
=> #201 cc changed

API/ControllerLogic/UserRegisterControllerLogic.cs, Email-Service/ActivateUser.cs, Libraries/DataLayer/Mongo/Entities/User.cs, Libraries/DataLayer/Mongo/Repositories/UserRepository.cs
=> sign token with RSA key from Rust and verify in rust.
